import { GetServerSideProps } from 'next';
import Head from 'next/head'
import { HomeContent } from '../contents/home'
import { useContext } from 'react';
import { AuthContext } from '../contexts/AuthContext';
import { withSession } from '../services/withSession';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContent />
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = withSession(async (ctx) => {
  return {
    props: {}, 
  }
})