import type { NextPage } from 'next'
import Head from 'next/head'
import { HomeContent } from '../contents/home'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContent />
    </div>
  )
}

export default Home
